### ISSUE TITLE
Extension not working on HTML/CSS

### ISSUE THREAD

**Issue by Nickynoir** [allemand-instable/Colorful-Comments#14]
Even though HTML/CSS Support is listed, for some reason the colors arent showing for me. Only in Languages like C, C# and so on
I only checked these so far so idk if the issue also persists on other languages

![image](https://github.com/user-attachments/assets/624d83ce-1e4d-4b0d-86f9-54ea857a49b6)
![image](https://github.com/user-attachments/assets/840d7e06-2197-4014-8553-259b1685f685)

**Comment by code-instable** [comment]
Hello it is working fine for me :

- html :
![image](https://github.com/user-attachments/assets/48194093-1083-4d45-98e5-2ecea759af46)
- css :
![image](https://github.com/user-attachments/assets/084968e3-2851-48d7-8876-9a7ddb3501c0)


Are you using the proper language identifier ?
![image](https://github.com/user-attachments/assets/50f7d117-75b0-49e1-bf77-2abe9b955bcf)

However I'm interested in more details if you still are not able to get it to work

**Comment by Nickynoir** [comment]
Thanks for replying! I just checked and turns out, HTML is actually working just fine. I thought you needed to use **/*** and not **<!--**. However, Functions like **// *** and **// ^** still arent working, even though im using the proper language identifier.
![image](https://github.com/user-attachments/assets/cef7a6bd-bf42-4866-991b-06675ed3ebe7)
![image](https://github.com/user-attachments/assets/1d87eef8-6bd0-490b-aae1-539ebec84230)

CSS on the otherhand was still not working for me. But turns out, that was because I had PostCSS as the language identifier, not the CSS from VSCode itself! But just like HTML, **// *** and **// ^** still arent working. But could it be because VSCode sees it as an error?
![image](https://github.com/user-attachments/assets/c0645e27-6166-4d6b-970b-b6bd6d3f2bcb)
![image](https://github.com/user-attachments/assets/a3ce7935-eb76-4f29-9b8f-de316af17d1f)

By the way, a couple questions: Do I need to have both the OG colorful comments and your colorful comments installed or can I uninstall the OG? And also, I think you should update the extension description too so people know what prefix to use in each programming language, so the ? and ! prefixes work

**Comment by code-instable** [comment]
I suggest you to uninstall the OG one, it is from the same code base but ahead in terms of new code for new features and languages.
If both are installed, they will try to fight each other

**Comment by code-instable** [comment]
`//` is not a valid html comment syntax, thus it won't work on html language id

**Comment by code-instable** [comment]
`//` is not a valid CSS comment syntax either, it works in certain css-preprocessors, but not vanilla CSS

**Comment by code-instable** [comment]
>  I think you should update the extension description too so people know what prefix to use in each programming language

To be honest, I don't think it's the package role to teach people what is the language's syntax
this package provides a way to add colors in comments

it therefore requires prior knowledge on the used language syntax, which can be learned in these languages docs or tutorials, in orde rto know how to make a proper comment in this language

I hope this helped you !
